num_episodes: 200
cost_weight: 3.0
risk_weight: 3.0
revisit_penalty: 2.0
lambda_cost: 0.0
eta_lambda: 0.05
cost_limit: 0.05
c1: 1.0
c2: 0.5
entropy_coef: 0.01
learning_rate: 0.0003
clip_epsilon: 0.2
gamma: 0.99
gae_lambda: 0.95
tau: 0.7
kappa: 4.0
initial_beta: 0.1
final_beta: 0.01
planner_bonus_decay: 1.0
H: 10
waypoint_bonus: 0.05
K: 0
world_model_lr: 0.001
danger_distance: 2
disable_icm: true
disable_rnd: true
disable_planner: true
